name: DevSecOps Engine Tools
on:
  push:
    branches:
      - main
env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
    
      - name: DET with branch
        continue-on-error: true
        run: |
          # Install devsecops-engine-tools
          pip3 install https://test-files.pythonhosted.org/packages/4f/06/aaac01b1b46007de9f30cbdb17ab9fbf010cd7f1a30e0d0fbcae7d981bae/devsecops_engine_tools-1.20.0-py3-none-any.whl
          output=$(devsecops-engine-tools --platform_devops github --remote_config_repo avengers --remote_config_branch feature/test_prerelease --tool engine_iac --folder_path .)
          echo "$output"
          if [[ $output == *"✘Failed"* ]]; then
            exit 1
          fi

      - name: DET without branch
        run: |
          # Install devsecops-engine-tools
          pip3 install https://test-files.pythonhosted.org/packages/4f/06/aaac01b1b46007de9f30cbdb17ab9fbf010cd7f1a30e0d0fbcae7d981bae/devsecops_engine_tools-1.20.0-py3-none-any.whl
          output=$(devsecops-engine-tools --platform_devops github --remote_config_repo avengers --tool engine_iac --folder_path .)
          echo "$output"
          if [[ $output == *"✘Failed"* ]]; then
            exit 1
          fi
