name: release

on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          zip -r rules_k8s rules/kubernetes
          zip -r rules_cft rules/cloudformation
          zip -r rules_docker rules/docker
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./rules_k8s.zip
            ./rules_cft.zip
            ./rules_docker.zip